### ISSUE TITLE
issues and edit point to nonexistent repository

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/ardusub-docs#8]
How to reproduce it:
1. Go to [ardusub.com](https://www.ardusub.com/operators-manual/flight-modes.html)
2. Click in Edit or Bug.
3. ~~Profit~~ [404 Error](https://github.com/jaxxzer/ardusub-gitbooks/)

**Comment by jaxxzer** [comment]
Fixed. This repository is retired, and we migrated to ardusub-gitbook.
